name = "ai-tech-review-public-metrics"
main = "src/worker.js"
compatibility_date = "2026-05-23"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "ai_tech_review_public_metrics"
database_id = "adf0da06-e5c1-479b-ad25-f9cc0a9522d8"

