from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak

ROOT=Path(__file__).resolve().parents[1]; PKG=ROOT/'2026-10-02_weekly-oled-inverse-design-triplet-state-control'
OUT=PKG/'artifacts/oled_inverse_design_weekly_brief_2026-10-02.pdf'; HERO=PKG/'artifacts/triplet_state_control_hero-web.webp'
ss=getSampleStyleSheet(); navy=colors.HexColor('#0b1b2b'); blue=colors.HexColor('#1267a1')
ss.add(ParagraphStyle(name='T',parent=ss['Title'],fontName='Helvetica-Bold',fontSize=25,leading=29,textColor=navy,spaceAfter=10))
ss.add(ParagraphStyle(name='H',parent=ss['Heading1'],fontName='Helvetica-Bold',fontSize=17,leading=21,textColor=navy,spaceBefore=8,spaceAfter=7))
ss.add(ParagraphStyle(name='S',parent=ss['Heading2'],fontName='Helvetica-Bold',fontSize=12.5,leading=16,textColor=blue,spaceBefore=6,spaceAfter=4))
ss.add(ParagraphStyle(name='B',parent=ss['BodyText'],fontName='Helvetica',fontSize=9.2,leading=13,spaceAfter=6,textColor=colors.HexColor('#1d2b36')))
ss.add(ParagraphStyle(name='C',parent=ss['BodyText'],fontName='Helvetica',fontSize=9,leading=13,backColor=colors.HexColor('#eaf3f8'),borderColor=colors.HexColor('#31a9d6'),borderWidth=.8,borderPadding=8,spaceAfter=8))
ss.add(ParagraphStyle(name='R',parent=ss['BodyText'],fontName='Helvetica',fontSize=8.6,leading=12,leftIndent=10,firstLineIndent=-10,spaceAfter=4))

def foot(c,d):
 c.saveState(); c.setStrokeColor(colors.HexColor('#cad9e3')); c.line(18*mm,13*mm,A4[0]-18*mm,13*mm); c.setFont('Helvetica',7); c.setFillColor(colors.grey); c.drawString(18*mm,8.5*mm,'Weekly OLED Inverse Design Brief | 2 October 2026'); c.drawRightString(A4[0]-18*mm,8.5*mm,str(d.page)); c.restoreState()

def section(story,title,meta,why,methods,results,limits,translation):
 story += [Paragraph(title,ss['S']),Paragraph(meta,ss['R']),Paragraph('<b>Why it matters.</b> '+why,ss['B']),Paragraph('<b>Methods.</b> '+methods,ss['B']),Paragraph('<b>Source-reported results.</b> '+results,ss['B']),Paragraph('<b>Limits.</b> '+limits,ss['B']),Paragraph('<b>Workflow translation (reviewer proposal).</b> '+translation,ss['B'])]

doc=SimpleDocTemplate(str(OUT),pagesize=A4,rightMargin=18*mm,leftMargin=18*mm,topMargin=17*mm,bottomMargin=18*mm,title='Weekly OLED Inverse Design Brief 2026-10-02',author='Hyun-Jung Kim')
s=[Paragraph('Triplet-State Control in Blue OLEDs and the Validation Chain for Molecular Inverse Design',ss['T']),Paragraph('Evidence window: 25 September–1 October 2026',ss['B']),Image(str(HERO),width=A4[0]-36*mm,height=(A4[0]-36*mm)*9/16),Spacer(1,7),Paragraph('The strongest evidence this week is a peer-reviewed blue-OLED study that treats the triplet manifold as a molecular design target and reports maximum EQE of 42.6%. Four adjacent records examine masked molecular inference, synthesis-defined search spaces, divide-and-conquer QSCI and constraint-preserving QAOA. Generation, electronic structure, synthesis, aggregation, device performance and quantum-resource claims remain separate validation gates.',ss['C']),Paragraph('Ranked shortlist',ss['H'])]
for x in ['1. <b>He, Zhang &amp; Li:</b> bridged-resonance blue OLED; EQEmax 42.6%.','2. <b>Li et al.:</b> CAGenMol-2 masked prediction, generation and local editing.','3. <b>Mahmood et al.:</b> synthesis-defined polymer-informatics roadmap.','4. <b>Tajima et al.:</b> Deep QSCI with 40→20-qubit register reduction in noiseless simulation.','5. <b>Stewart et al.:</b> constraint-preserving QAOA in A100 state-vector simulation.']: s.append(Paragraph(x,ss['R']))
s += [PageBreak(),Paragraph('1 | Direct OLED evidence',ss['H'])]
section(s,'Bridged resonance configuration enables high-efficiency and narrow-emission in blue organic light-emitting diodes','Yi-Hui He, Zhen Zhang, Yan-Qing Li · Nature Communications · 29 Sep 2026 · DOI 10.1038/s41467-026-78234-0','Triplet placement and return pathways govern accumulation, roll-off and degradation risk. This is the only record closing the loop through a device.','A bridged resonance configuration modulates triplet excited states while maintaining high photoluminescence quantum yield and narrow blue emission.','Maximum EQE 42.6%.','Peer-reviewed and directly relevant. Publisher full text redirected through authentication, so unverified ΔE_ST, k_RISC, linewidth and lifetime values were not added.','Store state ordering, transition-density localization, coupling proxies and conformer sensitivity; use fixed TDDFT/TDA screening, higher-level shortlist benchmarks, then film/device tests.')
s += [Paragraph('2 | Molecular generation and synthesis',ss['H'])]
section(s,'One Sequence, Many Decodings: CAGenMol-2 Recasts Drug Design as Masked Molecular Inference','Yanting Li et al. · arXiv:2609.34301v1 · 28 Sep 2026','One checkpoint changes tasks by changing the mask, useful for local donor, acceptor, bridge or host edits.','Wrapped SAFE molecules, five scalar slots and optional 3D pocket tokens; AdaFO performs gradient-free mask-and-refill search.','Single-property hit 0.89 ID / 0.72 OOD; joint hit 0.76 and 0.84; macro R² 0.910, Pearson 0.974; CrossDocked success 30.2%→70.8%, Vina −8.76 kcal/mol, high affinity 85.1%.','Drug-like/pocket preprint; confidence is not a calibrated posterior. SAFE validity, SA and docking do not prove synthesis or OLED properties.','Bind each target to method/environment, then independently validate TDDFT and reaction route.')
s += [PageBreak()]
section(s,'A roadmap for polymer informatics super-intelligence','Akhlak Mahmood et al. · arXiv:2609.34051v1 · 28 Sep 2026','The transferable principle is makeable-by-construction.','A roadmap linking representation, data, prediction, generation, retrosynthesis and agents.','Surveyed RxnChainer work: 44 reaction chains, 32 polymer classes, >289 million potentially makeable homopolymers. PolyBART example: Tg 595 K predicted versus 513 K experimental.','Perspective; numbers come from prior cited studies, not a new autonomous-lab benchmark.','Build OLED candidates from available blocks and validated coupling/borylation/SNAr routes before excited-state ranking.')
s += [Paragraph('3 | Quantum-method feasibility',ss['H'])]
section(s,'Divide-and-Conquer QSCI for π–π Stacking in the Benzene Dimer','Ryotaro Tajima et al. · arXiv:2609.36708v1 · 29 Sep 2026','Fragment reuse may help repeated host–guest calculations if classical and quantum costs are both counted.','One monomer QSCI is reused for both fragments and all separations; the effective Hamiltonian is classically diagonalized.','CAS(28e,20o) 40→20 qubits; Classiq noiseless simulation, 10⁴ shots/point and 5×10⁴ per scan; −0.908 versus CCSD(T) −1.139 kcal/mol at 4.0 Å; effective dimension 8,649.','No QPU. Different Hamiltonian/orbital/counterpoise treatments prevent quantitative validation; no runtime or advantage benchmark.','Use only as a small active-space benchmark beside SAPT, DLPNO-CCSD(T) or dispersion-corrected DFT.')
s += [PageBreak()]
section(s,'Quantum Approximate Optimisation Algorithm for Protein Sidechain Packing','Sebastian O. M. Stewart et al. · arXiv:2609.31077v1 · 25 Sep 2026','Shows how one-hot feasibility can be enforced structurally rather than by penalties.','W-state plus cyclic XY mixer conserves Hamming weight; gate scaling O(MN²)→O(MN).','A100/PennyLane simulation at 5–22 qubits, p≤12, 30 seeds. Fitted 99.99%-recovery budget <500 through 22 qubits, actual 22-qubit subsections ~52.5–732.9 shots. In 1,500 moderate-confidence runs, 54% beat the baseline; mean winning change −8.114 kcal/mol.','No QPU; StatePrep hides W-state preparation cost. The improvement reflects a weaker baseline, not quantum speedup.','Compare OLED one-hot QUBOs against simulated annealing, tabu search and CP-SAT with common metrics.')
s += [Paragraph('Practical experiment',ss['H']),Paragraph('Build a reaction-aware audit set around bridged-resonance chemistry: 20 MR-TADF scaffolds × ten route-bearing bridge or adjacent-substituent variants. Under one geometry protocol compute S1, T1, nearby Tn, oscillator strength and transition-density localization; add SOC/spin-vibronic proxies only for the top 20. Use scaffold-disjoint splits and compare generative confidence with independent TDDFT hit rate.',ss['C']),Paragraph('Read first',ss['H']),Paragraph('He, Zhang and Li. It is the only new record spanning synthesis, photophysics and an OLED device, and it makes the triplet manifold a primary molecular-design target.',ss['B']),Paragraph('Coverage gaps',ss['H']),Paragraph('No new PhOLED host, host–dopant/exciplex, OLED degradation, GW–BSE, SELFIES, CRBM/Boltzmann-machine, D-Wave/annealing or OLED-scale VQE work met the window. CAGenMol-2 uses SAFE. Both quantum papers are classical-simulator studies with no physical QPU or demonstrated advantage.',ss['B']),Paragraph('Sources',ss['H'])]
for r in ['1. https://doi.org/10.1038/s41467-026-78234-0','2. https://arxiv.org/abs/2609.34301','3. https://arxiv.org/abs/2609.34051','4. https://arxiv.org/abs/2609.36708','5. https://arxiv.org/abs/2609.31077']: s.append(Paragraph(r,ss['R']))
doc.build(s,onFirstPage=foot,onLaterPages=foot); print(OUT)
